id: P004311
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:09:43.351319
source_metadata:
  id: bdr:W1KG6328
  title: སྐྱབས་རྗེ་སེང་བྲག་རིན་པོ་ཆེ་མཆོག་གི་མཛད་རྣམ་མདོར་བསྡུས།
  author: ''
  volumes:
    4df0c694e5c84a3b8b0fb24683409f39:
      image_group_id: I1KG6332
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
