id: I622C9688
legacy_id: P004311
ocr_import_info:
  bdrc_scan_id: W1KG6328
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T05:39:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:49:12.030150+00:00'
last_modified: 2022-09-01 01:49:17.891143
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG6328
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG6328
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐྱབས་རྗེ་སེང་བྲག་རིན་པོ་ཆེ་མཆོག་གི་མཛད་རྣམ་མདོར་བསྡུས།
  author: མཁན་པོ་ཕྲིན་ལས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9575663802219462
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG6332:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG6332
      total_pages: 90
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG6332.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9575663802219462
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
