id: I622C9688
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:39:41+00:00'
last_modified: '2022-06-07T21:53:47.203228+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6328
  title: སྐྱབས་རྗེ་སེང་བྲག་རིན་པོ་ཆེ་མཆོག་གི་མཛད་རྣམ་མདོར་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0A40:
      image_group_id: I1KG6332
      title: ''
      total_pages: 90
      order: 1
      base_file: 0A40.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
